spring:
  datasource:
    username: root
    password: Zhr13926842++
    url: jdbc:mysql://192.168.18.131:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.18.130:8848
  application:
    name: gulimall-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000